* PSE Spotify mood tracker

** Spotify API
   Heeft mogelijkheid om laatste 50 tracks te weergeven.
   Track wordt toegevoegd aan de laatste 50 tracks na 30s luisteren
   Dus 50*30 = 25min minstens om weer 50 nieuwe tracks te analyseren.
   

** Web applicatie
   User logt in met spotify account, dan begint het tracken.
   User kan zien wat de moods zijn van de muziek die ze geluisterd hebben,
   bepaalde 'mood-patterns' 

** Minimal viable product

*** Data scrape van Spotify
    Voor elke user periodically de laatste 50 tracks aanvragen om zo een 
    grotere data sample te krijgen.

*** Interpretatie van data met Spotify API
    Spotify API geeft informatie als:
    energy, liveness, loudness, tempo, acousticness, danceability

    We moeten een interpretatie hiervan bedenken die in een 'emotie' kan
    worden samengevat. 
    
    Voor song-recommendations mogelijk eerst aanraden op basis van eerder
    geluisterde nummers. Later vanuit de hele Spotify library.

*** Interface om data te weergeven
    Eerst alle (relevante) data in simpele graphs weergeven, later kunnen
    we de data mooier maken. 
