from collections import defaultdict

from pydriller import RepositoryMining

REPO1 = "PSE-Backend"
REPO2 = "PSE-Frontend"
REPO3 = "PSE-Web"

# authors = defaultdict(list)
# for commit in RepositoryMining(REPO1).traverse_commits():
#     for modification in commit.modifications:
#         authors[commit.author.name].append(modification.filename)
#         # print('Author {} modified {} in commit {}'.format(commit.author.name, modification.filename))
# print("AB")
# for commit in RepositoryMining(REPO2).traverse_commits():
#     for modification in commit.modifications:
#         authors[commit.author.name].append(modification.filename)
# 
# print("DA")
# for commit in RepositoryMining(REPO3).traverse_commits():
#     for modification in commit.modifications:
#         authors[commit.author.name].append(modification.filename)
# 

aut = {'M Diallo': ['.gitignore', 'sql_login.sh', 'start_influx.sh', '.gitignore', 'README.md', 'feature_request.md',
                    'config.yml', '.gitignore', '.gitignore', 'config.js', '.gitignore', 'config.js', '.gitignore',
                    '.gitignore', 'README.md', '__init__.py', 'models.py', 'index.html', 'views.py', 'manage.py',
                    'README', 'alembic.ini', 'env.py', 'script.py.mako', 'ec762a3d649c_.py', 'run.py', '__init__.py',
                    'example_config.py', '__init__.py', 'models.py', '__init__.py', 'spotify.py', 'views.py',
                    'index.html', 'views.py', 'views.py', 'models.py', 'ccaa58ea613c_.py', 'requirements.txt',
                    'models.py', 'spotify.py', 'views.py', 'spotify.py', '__init__.py', 'models.py',
                    'font-awesome.min.css', 'ie8.css', 'ie9.css', 'main.css', 'noscript.css', 'FontAwesome.otf',
                    'fontawesome-webfont.eot', 'fontawesome-webfont.svg', 'fontawesome-webfont.ttf',
                    'fontawesome-webfont.woff', 'fontawesome-webfont.woff2', 'avatar.jpg', 'bg.jpg', 'logo.png',
                    'ssolarge.png', 'PIE.htc', 'html5shiv.js', 'respond.min.js', 'login.html', 'views.py', 'query.py',
                    'views.py', 'query.py', 'views.py', 'index.html', '.gitignore', '__init__.py', 'views.py',
                    '__init__.py', 'views.py', 'run.py', '__init__.py', 'models.py', 'run.py', '__init__.py',
                    '__init__.py', '__init__.py', '__init__.py', '__init__.py', 'models.py', 'models.py',
                    'requirements.txt', 'models.py', 'song_calls.py', 'models.py', 'song_calls.py', '__init__.py',
                    'user_calls.py', 'song_calls.py', 'models.py', 'user_calls.py', 'views.py', '__init__.py',
                    'playlist.py', 'song_calls.py', '__init__.py', 'playlist_calls.py', 'playlist_calls.py',
                    'index.html', 'playlist_calls.py', 'spotify.py', 'playlist_calls.py', 'user_calls.py',
                    'user_calls.py', 'user_calls.py', 'user_calls.py', 'user_calls.py', '__init__.py',
                    'playlist_calls.py', 'track_calls.py', 'user_calls.py', '__init__.py', 'views.py',
                    'example_config.py', 'import_moods.py', 'moodAnalysis.py', 'retrain_worker.py',
                    'update_moods_worker.py', 'update_tracks_worker.py', 'track_calls.py', 'exceptions.py', 'models.py',
                    'views.py', 'update_moods_worker.py', '__init__.py', 'playlist_calls.py', 'track_calls.py',
                    'user_calls.py', '__init__.py', 'influx.py', 'models.py', 'recommendations.py', 'spotify.py',
                    'tasks.py', 'views.py', 'import_moods.py', 'moodAnalysis.py', 'retrain_worker.py',
                    'update_moods_worker.py', 'update_tracks_worker.py', 'user_calls.py', 'user_calls.py'],
       'Jonasvdham': ['basicanalysis.py', 'moodAnalysis.org', '.#moodAnalysis.org', 'basicanalysis.py', 'data.csv',
                      'dataparse.py', 'moodAnalysis.org', '.#moodAnalysis.org', 'moods.csv', 'moods.csv',
                      'test_data.csv', 'titleretriever.py', 'gradientBoost.py', 'linearRegr.py', 'dataparse.py',
                      'translatedata.py', 'gradientBoost.py', 'gradientBoost.py', 'serverMoodAnalysis.py',
                      'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'serverMoodAnalysis.py',
                      'serverMoodAnalysis.py', 'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'takefeedback.py',
                      'gradientBoost.py', 'gradientBoost.py', 'gradientBoost.py', 'takefeedback.py',
                      'userfeedback.html', 'history.html', 'userfeedback.html', 'dashboard_layout.html', 'history.js',
                      'userfeedback.js', 'historybk2.html', 'history.js', 'userfeedback.js', 'history.html',
                      'history.css', 'history.js', 'userfeedback.js', 'history.html', 'history.js',
                      'songrecommendation.js', 'loadHistory.js', 'loadHistory.js', 'loadHistory.js', 'loadHistory.js',
                      'loadHistory.js', 'history.html', 'history.html', 'recommendation.html',
                      'songMetricRecommendation.js', 'recommendation.html', 'heatmap.js', 'heatmap.js', 'history.html',
                      'analytics.html', 'mood.html', 'recommendation.html', 'songMetricRecommendation.js',
                      'analytics.html', 'analyticsDescriptions.js', 'history.html', 'loadHistory.js',
                      'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'serverMoodAnalysis.py',
                      'serverMoodAnalysis.py', 'tasks.py', 'retrain_worker.py', 'retrain_worker.py',
                      'retrain_worker.py', 'retrain_worker.py', 'analyticsDescriptions.js', 'userfeedback.js',
                      'songrecommendation.js', 'import_moods.py', 'retrain_worker.py', 'loadHistory.js'],
       'Barry': ['titleretriever.py', '.gitignore', 'titleretriever.py', 'titleretriever.py',
                                       'titleretriever.py', 'test_data.csv', 'test_data.csv', 'data.csv',
                                       'titleretriever.py', 'data_parser.py', 'data_utrecht_parser.py',
                                       'spotify_data_parser.py', 'rfparser.py', 'rf_data.csv', 'data_utrecht_parser.py',
                                       'rfparser.py', 'spotify_data_parser.py', 'parsed_data.csv', 'random_forest.py',
                                       'random_forest.py', 'random_forest.py', 'rfparser.py', 'data_utrecht_parser.py',
                                       'data_utrecht_parser.py', 'moods_20.csv', 'analyzed_tracks_20.csv',
                                       'moods_20.csv', 'rf_data_20.csv', 'random_forest.py', 'data_utrecht_parser.py',
                                       'rfparser.py', 'spotify_data_parser.py', 'translatedata.py', 'dataparse.py',
                                       'random_forest.py', 'analyzed_tracks_20.csv', 'moods_20.csv',
                                       'moods_20_translated.csv', 'rf_data_20.csv', 'spotify_data_parser.py',
                                       'analyzed_tracks_0.csv', 'analyzed_tracks_20.csv', 'moods.csv', 'moods_0.csv',
                                       'moods_0_translated.csv', 'parsed_data.csv', 'rf_data.csv', 'rf_data_0.csv',
                                       'rf_data_20.csv', 'data_utrecht_parser.py', 'analyzed_tracks_0.csv',
                                       'analyzed_tracks_1.csv', 'moods_0.csv', 'moods_0_translated.csv', 'moods_1.csv',
                                       'moods_1_translated.csv', 'rf_data_0.csv', 'rf_data_1.csv', 'gradientBoost.py',
                                       'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'random_forest.py',
                                       'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'analyzed_tracks_20.csv',
                                       'moods_20_translated.csv', 'translatedata.py', 'gradientBoost.py',
                                       'random_forest.py', 'analyzed_tracks_1.csv', 'moods_1.csv',
                                       'moods_1_translated.csv', 'Trained-Energy.joblib', 'Trained-Happiness.joblib',
                                       'Trained-Energy.joblib', 'Trained-Happiness.joblib', 'analyzed_tracks_1.csv',
                                       'gradientBoost.py', 'spotify_data_parser.py', 'gradientBoost.py',
                                       'analyzed_tracks_1.csv', 'spotify_data_parser.py', 'analyzed_tracks_1.csv',
                                       'spotify_data_parser.py', 'analyzed_tracks_1.csv', 'spotify_data_parser.py',
                                       'random_forest.py', 'gradientBoost.py', 'linearRegr.py', 'random_forest.py',
                                       'serverMoodAnalysis.py', 'data_utrecht_parser.py', 'rfparser.py',
                                       'translatedata.py', 'translatedata.py', 'rfparser.py', 'translatedata.py',
                                       'spotify_data_parser.py', 'random_forest.py', 'serverMoodAnalysis.py',
                                       'data_utrecht_parser.py', 'spotify_data_parser.py', 'spotify_data_parser.py',
                                       'random_forest.py', 'data_utrecht_parser.py', 'spotify_data_parser.py',
                                       'loadLineCharts.js', 'history.html', 'history.js', 'history.js',
                                       'loadHistory.js', 'history.html', 'scripts.html', 'loadCharts.js',
                                       'loadHistory.js', 'history.html', 'recommendation.html', 'recommendation.html',
                                       'songMetricRecommendation.js', 'recommendation.html', 'songrecommendation.js',
                                       'main.css', 'history.html', 'scripts.html', 'loadHistory.js',
                                       'songMetricRecommendation.js', 'history.html', 'loadHistory.js',
                                       'loadHistory.js', 'history.html', 'loadHistory.js', 'history.html',
                                       'loadHistory.js', 'loadHistory.js', 'history.html', 'loadHistory.js',
                                       '_base.scss', 'history.html', 'recommendation.html', 'loadHistory.js',
                                       'loadHistory.js', 'history.html', 'loadHistory.js', 'history.html',
                                       'songrecommendation.js', 'history.html', 'main.css', 'main.css', 'history.html',
                                       'history.css', 'loadHistory.js', 'history.html', 'loadHistory.js',
                                       'history.html', 'loadHistory.js', 'loadHistory.js', 'tasks.py',
                                       'serverMoodAnalysis.py', 'serverMoodAnalysis.py', 'Trained-Excitedness.joblib',
                                       'Trained-Happiness.joblib', 'Trained-Excitedness.joblib',
                                       'Trained-Happiness.joblib', 'Trained-Excitedness.joblib',
                                       'Trained-Happiness.joblib', 'main.css', 'index.html', 'index.html', 'index.html',
                                       'chartText.js', 'chartText.js', 'index.html', 'heatmapData.js', 'loadRadar.js',
                                       'index.html', 'index.html', 'songMetricRecommendation.js', 'index.html',
                                       'songMetricRecommendation.js', 'recommendations.py',
                                       'songMetricRecommendation.js', 'loadHistory.js', 'songMetricRecommendation.js',
                                       'songMetricRecommendation.js', 'dashboard.html', 'loadHistory.js',
                                       'dashboard.html'],
       'jellewe': ['basicanalysis_v2.py', 'linechartDays.js', 'linechartDays.js', 'linechartDays.js',
                   'linechartSongs.js', 'loadLineCharts.js', 'linechartDays.js', 'linechartSongs.js',
                   'linechartDays.js', 'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'linechartDays.js',
                   'linechartSongs.js', 'analytics.html', 'history.html', 'call-to-action.html', 'header.html',
                   'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'userinput.js', 'analytics.html',
                   'scripts.html', 'linechartDays.js', 'linechartSongs.js', 'userinput.js', 'mood.html',
                   'recommendation.html', 'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js',
                   'analytics.html', 'scripts.html', 'barChart.js', 'loadLineCharts.js', 'barChart.js', 'barChart.js',
                   'loadLineCharts.js', 'analytics.html', 'scripts.html', 'analyticsDescriptions.js',
                   'loadLineCharts.js', 'analyticsDescriptions.js', 'analytics.html', 'loadLineCharts.js',
                   'linechartDays.js', 'linechartSongs.js', 'linechartDays.js', 'linechartSongs.js', 'userinput.js',
                   'd3v3.min.js', 'd3v4.min.js', 'linechart.js', 'linechart.js', 'linechart.js', 'index.html',
                   'linechart.css', 'linechart.js', 'linechart.css', 'linechart.js', 'linechart.css', 'linechart.js',
                   'linechart.js', 'linechart.js', 'heatmap2.js', 'radarChart.js', 'index.html', 'style.css',
                   'heatmap2.js', 'style.css', 'linechart.js', 'linechart.js', 'index.html', 'linechart.js',
                   'index.html', 'linechart.css', 'style.css', 'linechart.js', 'linechart.js', 'linechart.js',
                   'linechart.js', 'index.html', 'buttons.js', 'linechart.js', 'linechart.js', 'linechart.js',
                   'buttons.js', 'linechart.js', 'linechart.js', 'linechart.js', 'buttons.js', 'linechartDays.js',
                   'linechartSongs.js', 'index.html', 'linechartDays.js', 'index.html', 'linechartDays.js',
                   'linechartSongs.js', 'buttons.js', 'linechartDays.js', 'linechartSongs.js', 'linechartDays.js',
                   'linechartSongs.js', 'buttonToggles.js', 'linechartDays.js', 'linechartSongs.js', 'dashboard.html'],
       'Youri Reijne': ['query.py', 'query.py', 'README.md', '.gitignore', 'encodings.xml', 'gradle.xml', 'misc.xml',
                        'runConfigurations.xml', 'vcs.xml', '.gitignore', 'build.gradle', 'proguard-rules.pro',
                        'ExampleInstrumentedTest.java', 'AndroidManifest.xml', 'DashboardActivity.java',
                        'DataObject.java', 'LandingActivity.java', 'TestActivity.java', 'ic_launcher_foreground.xml',
                        'ic_launcher_background.xml', 'ic_menu_camera.xml', 'ic_menu_gallery.xml', 'ic_menu_manage.xml',
                        'ic_menu_send.xml', 'ic_menu_share.xml', 'ic_menu_slideshow.xml', 'side_nav_bar.xml',
                        'activity_dashboard.xml', 'activity_landing.xml', 'activity_test.xml', 'app_bar_test.xml',
                        'content_test.xml', 'nav_header_test.xml', 'activity_test_drawer.xml', 'test.xml',
                        'ic_launcher.xml', 'ic_launcher_round.xml', 'ic_launcher.png', 'ic_launcher_round.png',
                        'ic_launcher.png', 'ic_launcher_round.png', 'ic_launcher.png', 'ic_launcher_round.png',
                        'ic_launcher.png', 'ic_launcher_round.png', 'ic_launcher.png', 'ic_launcher_round.png',
                        'styles.xml', 'colors.xml', 'dimens.xml', 'strings.xml', 'styles.xml', 'ExampleUnitTest.java',
                        'build.gradle', 'gradle.properties', 'gradle-wrapper.jar', 'gradle-wrapper.properties',
                        'gradlew', 'gradlew.bat', 'settings.gradle', 'data.json', 'radarChart.js', 'testchar.html',
                        'style.css', 'dummydata.json', 'favicon.ico', 'index.html', 'radarChart.js', 'barChartH.js',
                        'barChartV.js', 'styles.css', 'exampleData.csv', 'login.html', 'pieChart.html', 'pieChart.js',
                        'tests.html', 'www', 'www', 'www', '.gitignore', '_base.scssc', '_mixins.scssc', 'LICENCE',
                        'README.md', '_config.yml', 'analytics.html', 'aside.html', 'call-to-action.html',
                        'contact.html', 'dashboard_scripts.html', 'head.html', 'header.html', 'history.html',
                        'login.html', 'mood.html', 'nav.html', 'nav_minimal.html', 'nav_welcome.html', 'portfolio.html',
                        'recommendation.html', 'scripts.html', 'services.html', 'dashboard_layout.html', 'front.html',
                        'login_layout.html', '_base.scss', '_mixins.scss', 'animate.min.css', 'bootstrap.css',
                        'bootstrap.min.css', 'main.scss', 'dashboard.html', 'font-awesome.css', 'font-awesome.min.css',
                        'animated.less', 'bordered-pulled.less', 'core.less', 'fixed-width.less', 'font-awesome.less',
                        'icons.less', 'larger.less', 'list.less', 'mixins.less', 'path.less', 'rotated-flipped.less',
                        'stacked.less', 'variables.less', '_animated.scss', '_bordered-pulled.scss', '_core.scss',
                        '_fixed-width.scss', '_icons.scss', '_larger.scss', '_list.scss', '_mixins.scss', '_path.scss',
                        '_rotated-flipped.scss', '_stacked.scss', '_variables.scss', 'font-awesome.scss',
                        'GothamMedium.eot', 'GothamMedium.svg', 'GothamMedium.ttf', 'GothamMedium.woff',
                        'GothamMedium.woff2', 'GothamMediumItalic.ttf', 'GothamMedium_1.ttf', 'header.jpg',
                        'header_black_disk.png', 'header_neon_headphones.jpg', 'logo_v2.png', 'moodify_logo_v2.png',
                        'moodify_logo_v2_transparant.png', '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg',
                        'index.html', 'bootstrap.js', 'bootstrap.min.js', 'cbpAnimatedHeader.js', 'classie.js',
                        'creative.js', 'jquery.easing.min.js', 'jquery.fittext.js', 'jquery.js', 'wow.min.js',
                        'login.html', '_config.yml', 'contact.html', '_base.scss', 'envelope.png', 'github.svg',
                        'analytics.html', 'history.html', 'contact.html', 'mood.html', 'nav.html', 'header.html',
                        'nav_welcome.html', 'header.jpg', 'header_neon_headphones.jpg', 'logo_v2.png',
                        'moodify_logo_v2.png', 'moodify_logo_v2_transparant.png', 'mood.html', 'dashboard_layout.html',
                        '_base.scss', 'main.css', 'heatmap.js', 'nav.html', 'dashboard_layout.html', 'loadRadar.js',
                        'mood.html', 'main.css', 'loadRadar.js', 'analytics.html', '_base.scss', 'analytics.html',
                        'dashboard_layout.html', 'slider.css', 'dashboard_layout.html', 'nav.html', 'header.html',
                        'nav_welcome.html', 'models.py', 'tasks.py', 'views.py', 'run.py', 'tasks.py', 'views.py',
                        'models.py', 'tasks.py', 'c3d17df8f564_.py', 'models.py', 'tasks.py', 'models.py', 'models.py',
                        '5829cc457eed_.py', 'c3d17df8f564_.py', 'ccaa58ea613c_.py', 'ec762a3d649c_.py', 'models.py',
                        'models.py', 'models.py', '__init__.py', '__init__.py', '__init__.py', '__init__.py',
                        '__init__.py', 'models.py', 'REST.py', 'tasks.py', 'cd97d4a1d041_.py', 'worker.py', 'REST.py',
                        'models.py', 'REST.py', 'models.py', 'song_recommendations.py', 'tasks.py',
                        'song_recommendations.py', 'REST.py', 'models.py', 'models.py', 'tasks.py', 'test_sql.py',
                        '60423d1c5af4_.py', '6424bb3a1b5c_.py', 'fb7da4962d13_.py', 'models.py', 'tasks.py',
                        'test_sql.py', 'tasks.py', 'tasks.py', '__init__.py', 'history_name.py', 'metric_name.py',
                        'recommendation.py', 'tracks.py', 'user_name.py', 'users.py', 'test_sql.py', 'models.py',
                        'tasks.py', 'tasks.py', 'tasks.py', 'moodAnalysis.py', 'tasks.py', 'tracks.py', 'users.py',
                        '__init__.py', 'track_calls.py', 'user_calls.py', 'track_calls.py', 'models.py', 'tasks.py',
                        'track_calls.py', 'models.py', 'tasks.py', 'eee6179bdafa_.py', 'track_calls.py',
                        'track_calls.py', 'track_calls.py', 'track_calls.py', 'track_calls.py', 'user_calls.py',
                        'track_calls.py', 'user_calls.py', 'track_calls.py', 'song_calls.py', 'track_calls.py',
                        'models.py', 'track_calls.py', 'tasks.py', 'tasks.py', 'tasks.py', 'track_calls.py', 'tasks.py',
                        'track_calls.py', 'track_calls.py', 'user_calls.py', 'tasks.py', 'user_calls.py',
                        'track_calls.py', 'user_calls.py', 'index.html', 'track_calls.py', 'user_calls.py', 'tasks.py',
                        'track_calls.py', 'track_calls.py', 'user_calls.py', 'models.py', '__init__.py',
                        'playlist_calls.py', 'song_calls.py', 'track_calls.py', 'user_calls.py', 'models.py',
                        'user_calls.py', 'user_calls.py', 'models.py', 'track_calls.py', 'user_calls.py',
                        'dashboard.html', 'index.html', 'nohup.out', '__init__.py', 'main.css', 'slider.css',
                        'history.css', 'main.css', 'font-awesome.min.css', 'envelope.png', 'envelope.svg', 'github.svg',
                        'header.jpg', 'header_neon_headphones.jpg', 'logo_v2.png', 'moodify_logo_v2.png',
                        'moodify_logo_v2_transparant.png', 'navbar_moodify_logo.png', 'analyticsDescriptions.js',
                        'barChart.js', 'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'userinput.js',
                        'loadHistory.js', 'heatmap.js', 'history.js', 'loadCharts.js', 'loadRadar.js', 'radarChart.js',
                        'songMetricRecommendation.js', 'songrecommendation.js', 'userinput.js', 'LICENCE', 'README.md',
                        'dashboard.html', 'index.html', 'login.html', 'dashboard.html', 'dashboard.html',
                        'dashboard.html', 'chartText.js', 'chartText.js', 'chartText.js', 'playlist_calls.py',
                        'track_calls.py', 'user_calls.py', 'chartText.js', 'loadHistory.js',
                        'songMetricRecommendation.js', 'dashboard.html'],
       'mounir': ['sql_login.sh', 'start_influx.sh', '.gitignore', '_base.scssc', '_mixins.scssc', 'analytics.html',
                  'history.html', 'mood.html', 'nav.html', 'recommendation.html', 'scripts.html',
                  'dashboard_scripts.html', 'history.html', 'call-to-action.html', 'contact.html', 'header.html',
                  'nav_welcome.html', 'mood.html', 'recommendation.html', 'aside.html', 'login.html',
                  'nav_minimal.html', 'portfolio.html', 'services.html', 'dashboard_layout.html', 'front.html',
                  'login.html', 'login_layout.html', 'analytics.html', 'history.html', 'mood.html',
                  'recommendation.html', 'launch.json', 'mood.html', 'main.css', 'heatmap.js', 'loadCharts.js',
                  'head.html', 'history.html', 'mood.html', 'scripts.html', 'dashboard_layout.html', 'heatmap.css',
                  'main.css', 'favicon.ico', 'glyphicons-halflings-regular.eot', 'glyphicons-halflings-regular.svg',
                  'glyphicons-halflings-regular.ttf', 'glyphicons-halflings-regular.woff',
                  'glyphicons-halflings-regular.woff2', 'chartText.js', 'heatmap.js', 'loadCharts.js', 'loadRadar.js',
                  'radarChart.js', 'analytics.html', 'mood.html', 'main.css', 'charts.js', 'chartText.js', 'heatmap.js',
                  'loadCharts.js', 'analytics.html', 'main.css', 'analytics.html', 'history.html', 'mood.html',
                  'recommendation.html', 'scripts.html', '_base.scss', 'main.css', 'creative.js', 'charts.js',
                  'linechartDays.js', 'linechartSongs.js', 'loadLinecharts.js', 'heatmap.js', 'loadCharts.js',
                  'analytics.html', 'analytics.html', 'spotify.py', 'tasks.py', 'serverMoodAnalysis.py', 'worker.py',
                  'track_calls.py', 'track_calls.py', 'track_calls.py', 'models.py', 'import_moods.py', 'style.css',
                  'index.html', 'index.js', 'views.py', 'style.css', 'songMetricRecommendation.js', 'getTop10.js',
                  'index.html', 'index.js', 'songMetricRecommendation.js','tasks.py', 'tasks.py', 'tasks.py', 'Trained-Excitedness.joblib', 'serverMoodAnalysis.py',
                            'serverMoodAnalysis.py', 'style.css', 'loadRadar.js', '__init__.py', 'loadRadar.js',
                            'views.py', 'REST.py', 'import_sql.py', 'out.json', 'out.txt', 'REST.py', 'out.json',
                            'out.txt', 'views.py', 'song_recommendations.py', 'song_recommendations.py', 'REST.py',
                            'moodAnalysis.py', 'moodAnalysis.py', 'REST.py','query.py', 'query.py', 'query.py', 'main.css', 'main.css', 'analytics.html', 'recommendation.html',
                  'scripts.html', 'scripts.html', 'main.css', 'linechartDays.js', 'loadLineCharts.js', 'chartText.js',
                  'loadCharts.js', 'songMetricRecommendation.js', 'songrecommendation.js', 'recommendation.html',
                  'scripts.html', 'linechartDays.js', 'loadCharts.js', 'songrecommendation.js', 'recommendation.html',
                  'contact.html', '_base.scss', 'main.css', 'main.scss', 'analytics.html', 'mood.html', 'main.css',
                  'loadHistory.js', 'analytics.html', 'head.html', 'history.html', 'mood.html', 'recommendation.html',
                  'scripts.html', 'head.html', 'scripts.html', '_base.scss', 'main.css', 'slider.css', 'analytics.js',
                  'linechartDays.js', 'userinput.js', 'chartText.js', 'loadCharts.js', 'analytics.html', 'nav.html',
                  'recommendation.html', 'scripts.html', 'head.html', 'main.css', 'slider.css', 'cow_logo.png',
                  'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'userinput.js', 'loadHistory.js',
                  'heatmap.js', 'history.js', 'loadCharts.js', 'userfeedback.js', 'songMetricRecommendation.js',
                  'songrecommendation.js', 'loadHistory.js', 'scripts.html', 'loadHistory.js', 'userinput.js',
                  'loadHistory.js', 'index.html', 'visualisation.js', 'index.html', 'query.py', 'index.js', 'views.py',
                  'query.py', 'index.js', 'views.py', 'views.py', 'index.js', 'index.js', 'index.js', 'index.js',
                  'index.js', 'views.py', 'tasks.py', 'tasks.py', 'tasks.py', 'views.py', 'worker2.py', 'tasks.py',
                  'views.py', 'tasks.py', 'views.py', 'tasks.py', 'tasks.py', 'views.py', 'models.py', 'tasks.py',
                  'views.py', 'worker2.py', 'views.py', 'tasks.py', '__init__.py', '__init__.py', '__init__.py',
                  '__init__.py', 'animate.min.css', 'bootstrap.css', 'bootstrap.min.css', 'heatmap.css', 'main.css',
                  'slider.css', 'font-awesome.min.css', 'history.css', 'ie8.css', 'ie9.css', 'linechart.css',
                  'main.css', 'noscript.css', 'songMetric.css', 'style.css', 'userfeedback.css', 'favicon.ico',
                  'font-awesome.css', 'font-awesome.min.css', 'animated.less', 'bordered-pulled.less', 'core.less',
                  'fixed-width.less', 'font-awesome.less', 'icons.less', 'larger.less', 'list.less', 'mixins.less',
                  'path.less', 'rotated-flipped.less', 'stacked.less', 'variables.less', 'font-awesome.scss',
                  'FontAwesome.otf', 'GothamMedium.eot', 'GothamMedium.svg', 'GothamMedium.ttf', 'GothamMedium.woff',
                  'GothamMedium.woff2', 'GothamMediumItalic.ttf', 'GothamMedium_1.ttf', 'fontawesome-webfont.eot',
                  'fontawesome-webfont.svg', 'fontawesome-webfont.ttf', 'fontawesome-webfont.woff',
                  'fontawesome-webfont.woff2', 'glyphicons-halflings-regular.eot', 'glyphicons-halflings-regular.svg',
                  'glyphicons-halflings-regular.ttf', 'glyphicons-halflings-regular.woff',
                  'glyphicons-halflings-regular.woff2', 'avatar.jpg', 'bg.jpg', 'cow_logo.png', 'envelope.png',
                  'favicon.ico', 'github.svg', 'header.jpg', 'header_black_disk.png', 'header_neon_headphones.jpg',
                  'logo-old.png', 'logo.png', 'logo_v2.png', 'moodify_logo_v2.png', 'moodify_logo_v2_transparant.png',
                  '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', 'ssolarge.png', 'PIE.htc', 'bootstrap.js',
                  'bootstrap.min.js', 'buttons.js', 'cbpAnimatedHeader.js', 'classie.js', 'creative.js', 'd3v3.min.js',
                  'd3v4.min.js', 'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'userinput.js',
                  'barChart.js', 'loadHistory.js', 'chartText.js', 'heatmap.js', 'history.js', 'loadCharts.js',
                  'loadRadar.js', 'radarChart.js', 'userfeedback.js', 'songMetricRecommendation.js',
                  'songrecommendation.js', 'heatmap2.js', 'heatmapData.js', 'html5shiv.js', 'index.js',
                  'jquery.easing.min.js', 'jquery.fittext.js', 'jquery.js', 'loadRadar.js', 'mainPage.js',
                  'respond.min.js', 'songMetricRecommendation.js', 'songrecommendation.js', 'wow.min.js',
                  'dashboard.html', 'getTop10.js', 'index.html', 'index.js', 'logout.html', 'visualisation.js',
                  'views.py', '__init__.py', 'analyticsDescriptions.js', 'linechartDays.js', 'linechartSongs.js',
                  'loadLineCharts.js', 'loadHistory.js', 'loadCharts.js', 'songMetricRecommendation.js',
                  'linechartSongs.js', 'loadHistory.js', 'linechartSongs.js', 'linechartSongs.js', 'linechartSongs.js',
                  'linecharts.js', 'dashboard.html', 'launch.json', 'linecharts.js', 'loadLineCharts.js',
                  'loadHistory.js', 'loadCharts.js', 'loadHistory.js', 'dashboard.html'],
       'Esmeralda': ['song_recommendations.py', 'tasks.py', 'tasks.py', 'tasks.py', 'tasks.py', 'tasks.py'],
       'HNegus': ['README.md', '.gitignore', 'encodings.xml', 'gradle.xml', 'misc.xml', 'runConfigurations.xml',
                  'vcs.xml', '.gitignore', 'build.gradle', 'proguard-rules.pro', 'ExampleInstrumentedTest.java',
                  'AndroidManifest.xml', 'DashboardActivity.java', 'LandingActivity.java', 'TestActivity.java',
                  'ic_launcher_foreground.xml', 'ic_launcher_background.xml', 'ic_menu_camera.xml',
                  'ic_menu_gallery.xml', 'ic_menu_manage.xml', 'ic_menu_send.xml', 'ic_menu_share.xml',
                  'ic_menu_slideshow.xml', 'side_nav_bar.xml', 'activity_dashboard.xml', 'activity_landing.xml',
                  'activity_test.xml', 'app_bar_test.xml', 'content_test.xml', 'nav_header_test.xml',
                  'activity_test_drawer.xml', 'test.xml', 'ic_launcher.xml', 'ic_launcher_round.xml', 'ic_launcher.png',
                  'ic_launcher_round.png', 'ic_launcher.png', 'ic_launcher_round.png', 'ic_launcher.png',
                  'ic_launcher_round.png', 'ic_launcher.png', 'ic_launcher_round.png', 'ic_launcher.png',
                  'ic_launcher_round.png', 'styles.xml', 'colors.xml', 'dimens.xml', 'strings.xml', 'styles.xml',
                  'ExampleUnitTest.java', 'build.gradle', 'gradle.properties', 'gradle-wrapper.jar',
                  'gradle-wrapper.properties', 'gradlew', 'gradlew.bat', 'settings.gradle', 'DataObject.java',
                  'TestActivity.java', 'activity_test.xml', 'TestActivity.java', 'loadCharts.js', 'history.js',
                  'history.html', 'scripts.html', 'analytics.html', 'analytics.js', 'loadCharts.js', 'scripts.html',
                  'userfeedback.html', 'dashboard_layout.html', 'userfeedback.css', 'userfeedback.js', 'scripts.html',
                  'history.css', 'heatmap.js', 'history.js', 'history.html', 'scripts.html', 'userfeedback.html',
                  'head.html', 'scripts.html', 'history.js', 'history.html', 'history.js', 'history.html', 'history.js',
                  'history.html', 'recommendation.html', '_base.scss', 'main.css', 'linechartDays.js',
                  'linechartSongs.js', 'loadLineCharts.js', 'history.js', 'history.html', 'scripts.html',
                  'userfeedback.html', 'head.html', 'scripts.html', 'history.js', 'history.html', 'recommendation.html',
                  '_base.scss', 'main.css', 'linechartDays.js', 'linechartSongs.js', 'loadLineCharts.js', 'history.js',
                  'history.html', 'history.html', 'scripts.html', 'userfeedback.html', 'head.html', 'scripts.html',
                  'history.js', 'history.js', 'history.js', 'history.html', 'history.js', 'history.css', 'history.css',
                  'history.js', 'history.html', 'history.css', 'history.js', 'history.html', 'history.js',
                  'history.html', 'history.html', 'history.html', 'loadHistory.js', 'history.html', 'nav.html',
                  'analytics.html', 'history.html', 'history.css', 'loadHistory.js', 'history.html', 'loadHistory.js',
                  'history.html', 'loadHistory.js', 'history.html', 'history.css', 'loadHistory.js', 'history.html',
                  'history.css', 'views.py', 'loadRadar.js', 'index.html', 'influx.py', 'views.py', 'tasks.py',
                  'influx.py', 'views.py', 'style.css', 'index.js', 'index.html', 'views.py', 'track_calls.py',
                  'influx.py', 'influx.py', 'influx.py', 'influx.py', 'loadHistory.js', 'userinput.js', 'userinput.js',
                  'userinput.js', 'loadHistory.js', 'userinput.js', 'barChart.js', 'barChart.js', 'loadHistory.js',
                  'userinput.js', 'user_calls.py', 'models.py', 'tasks.py', 'views.py', 'barChart.js', 'barChart.js',
                  'loadHistory.js', 'userinput.js'],
       'Arthur': ['barChartH.js', 'barChartV.js', 'styles.css', 'login.html', 'stats.html',
                          'codeStyleConfig.xml', 'modules.xml', 'pse.iml', 'vcs.xml', 'workspace.xml', 'barChartV.js',
                          'exampleData.csv', 'stats.html', 'tests.html', 'workspace.xml', 'styles.css',
                          'exampleData.csv', 'login.html', 'pieChart.html', 'pieChart.js', 'stats.html', 'tests.html',
                          'workspace.xml', 'styles.css', 'pieChart.html', 'pieChart.js', 'workspace.xml', 'login.html',
                          'pieChart.html', 'pieChart.js', 'chartText.js', 'barChart.js', 'heatmap.js', 'heatmap.js',
                          'loadCharts.js', 'loadRadar.js', 'barChart.js', 'loadCharts.js', 'barChart.js',
                          'analytics.html', 'barChart.js', 'loadLineCharts.js', 'barChart.js', 'style.css',
                          'chartText.js', 'heatmap2.js', 'linechart.js', 'loadRadar.js', 'mainPage.js', 'radarChart.js',
                          'index.html', 'style.css', 'index.html', 'style.css', 'mainPage.js', 'index.html', 'index.js',
                          'style.css', 'mainPage.js', 'index.html', 'style.css', 'index.html', 'songMetric.css',
                          'songMetricRecommendation.js', 'songrecommendation.js', 'index.html', 'index.html',
                          'linechart.css', 'index.html'],
       'Siwa': ['.DS_Store', 'data.json', 'testchar.html', 'data.json', 'radarChart.js', 'testchar.html',
                    'style.css', 'dummydata.json', 'favicon.ico', 'index.html', 'radarChart.js', 'history.html',
                    'historybk2.html', 'history.css', 'userfeedback.css', 'history.js', 'userfeedback.js',
                    'history.html', 'style.css', 'favicon.ico', 'loadRadar.js', 'radarChart.js', 'dummydata.json',
                    'index.html', 'views.py', 'example_config.py', 'query.py', 'loadRadar.js', 'index.html',
                    'loadRadar.js', 'views.py', 'loadRadar.js', 'index.html', 'views.py', 'd3v3.min.js', 'd3v4.min.js',
                    'heatmap2.js', 'heatmapData.js', 'linechart.js', 'loadRadar.js', 'radarChart.js', 'dummydata.json',
                    'index.html', 'heatmapData.js', 'linechart.js', 'loadRadar.js', 'index.html', 'views.py',
                    'style.css', 'loadRadar.js', 'index.html', 'index.html', 'style.css', 'index.html', 'style.css',
                    'index.html', 'logout.html', 'views.py', 'main.css', 'noscript.css', 'style.css', 'logo-old.png',
                    'logo.png', 'index.html', 'index.js', 'login.html', 'style.css', 'index.html',
                    'songrecommendation.js', 'style.css', 'loadRadar.js', 'songrecommendation.js', 'index.html',
                    'index.html', 'songrecommendation.js', 'index.html', 'views.py', 'views.py', 'style.css',
                    'loadRadar.js', 'index.html', '.DS_Store', '.DS_Store', 'songrecommendation.js', 'track_calls.py',
                    'style.css', 'songrecommendation.js', 'index.html', 'views.py', 'track_calls.py', 'index.html',
                    'index.js', 'track_calls.py', 'songrecommendation.js', 'index.html', 'index.html', 'style.css',
                    'index.html', 'style.css', 'songrecommendation.js', 'loadRadar.js', 'loadHistory.js',
                    'loadRadar.js', 'loadRadar.js'],
       'Elijah': ['recommendation.html', 'call-to-action.html', 'header.html', 'tasks.py', 'tasks.py', 'tasks.py'],
       'Mitchell': ['nav.html', 'navbar_moodify_logo.png', 'style.css', 'chartText.js', 'index.html', 'chartText.js',
                    'style.css', 'chartText.js', 'index.html', 'chartText.js', 'chartText.js', 'index.html',
                    'radarChart.js', 'index.html', 'chartText.js', 'radarChart.js', 'index.html', 'chartText.js',
                    'chartText.js', 'chartText.js', 'chartText.js', 'buttons.js', 'index.html', 'index.html', 'ie9.css',
                    'buttons.js', 'index.html', 'buttons.js', 'buttons.js', 'buttons.js', 'buttons.js', 'buttons.js',
                    'buttons.js', 'buttons.js', 'settings.json', 'chartText.js', 'loadRadar.js', 'chartText.js',
                    'heatmap.js', 'loadCharts.js', 'radarChart.js'],
       'Stan van den Broek': ['spotify.py', '__init__.py', 'models.py', 'tasks.py', 'views.py', 'example_config.py',
                              'worker.py', 'spotify.py', 'tasks.py', 'worker.py', 'spotify.py', 'tasks.py', 'views.py',
                              'manage.py', 'query.py', 'run.py', 'worker.py', 'views.py', 'query.py', 'tasks.py',
                              'views.py', '__init__.py', '__init__.py', 'test_app.py', '__init__.py', 'test_app.py',
                              'views.py', 'run.py', 'run.py', 'tasks.py', 'test_app.py', 'tasks.py', 'moodAnalysis.py',
                              'serverMoodAnalysis.py', 'run.py', 'update_mood.py', 'update_tracks.py', 'REST.py',
                              '__init__.py', 'influx.py', '__init__.py', 'models.py', 'tasks.py', 'views.py',
                              'query.py', 'worker.py', 'update_mood.py', 'tasks.py', 'update_moods.py', 'worker.py',
                              'tasks.py', 'spotify.py', 'tasks.py', 'views.py', 'worker.py', 'REST.py', 'exceptions.py',
                              'spotify.py', 'worker.py', 'REST.py', 'exceptions.py', 'spotify.py', 'tasks.py',
                              'moodAnalysis.py', 'worker.py', 'tasks.py', 'REST.py', 'test_simple_login.py', 'views.py',
                              'test_simple_login.py', 'exceptions.py', 'spotify.py', 'test_simple_login.py',
                              'moodAnalysis.py', 'REST.py', '__init__.py', 'history_name.py', 'metric_name.py',
                              'mood_name.py', 'recommendation.py', 'user_name.py', '__init__.py',
                              'song_recommendations.py', 'test_sql.py', '__init__.py', 'exceptions.py', 'influx.py',
                              'models.py', 'spotify.py', 'tasks.py', 'views.py', 'import_sql.py',
                              'update_moods_worker.py', 'update_tracks_worker.py', 'tracks.py', 'users.py',
                              'test_spotify_queue.py', 'tasks.py', 'views.py', 'moodAnalysis.py',
                              'test_spotify_queue.py', 'test_simple_login.py', 'test_sql.py', 'test_utils_models.py',
                              'test_utils_spotify.py', 'test_utils_tasks.py', 'test_views.py', '__init__.py',
                              'playlist.py', 'song_calls.py', 'track_calls.py', 'tracks.py', 'user_calls.py',
                              'influxdb.conf.template', 'test_utils_influx.py', 'exceptions.py', 'influx.py',
                              'recommendations.py', 'tasks.py', 'views.py', 'import_moods.py', 'retrain_worker.py',
                              'run.py', 'influxdb.conf.template', 'test_utils_influx.py', 'test_utils_models.py',
                              'test_utils_tasks.py', 'models.py', 'presets.py', 'test_utils_influx.py',
                              'test_utils_models.py', 'influx.py', 'models.py', 'views.py', '.gitignore',
                              'songMetricRecommendation.js', 'songrecommendation.js', 'index.html',
                              'test_utils_influx.py', 'test_utils_models.py', 'test_views.py', 'recommendations.py',
                              'tasks.py', 'views.py', 'import_moods.py', 'test_utils_models.py', 'playlist.py',
                              'index.js', 'test_utils_influx.py', 'test_utils_spotify.py', 'influx.py', 'spotify.py',
                              'track_calls.py', 'user_calls.py', 'test_utils_influx.py', 'test_utils_models.py',
                              'influx.py', 'models.py', 'tasks.py', 'views.py', 'update_moods_worker.py', 'influx.py',
                              'tasks.py', '.travis.yml', '.travis.yml', 'test_API_calls.py', 'test_utils_spotify.py',
                              'test_utils_tasks.py', 'test_views.py', 'influx.py', 'pytest.ini', '.travis.yml',
                              'example_config.py', 'requirements.txt', '.travis.yml', '.travis.yml', '.travis.yml',
                              '.travis.yml', '.travis.yml', '.travis.yml', '.travis.yml', '.travis.yml', '.travis.yml',
                              '.travis.yml', '.travis.yml', '.travis.yml', 'README.md', 'playlist_calls.py',
                              'test_API_calls.py', 'test_utils_tasks.py', 'k3_album.py', 'multiple_users.py',
                              'k3_album.py', 'multiple_songs.py', 'presets.py', 'test_utils_influx.py', 'presets.py',
                              'test_API_calls.py', 'influx.py', 'pytest.ini', 'track_calls.py', 'presets.py',
                              'test_API_calls.py', 'influx.py', 'user_calls.py', 'test_API_calls.py', 'test_views.py',
                              'playlist_calls.py', 'track_calls.py', 'user_calls.py', '__init__.py', 'presets.py',
                              'test_API_calls.py', 'test_utils_influx.py', 'test_utils_models.py', 'test_views.py',
                              'exceptions.py', 'influx.py', 'models.py', 'recommendations.py', 'spotify.py', 'tasks.py',
                              'retrain_worker.py', 'k3_album.py', 'test_API_calls.py', 'models.py', 'models.py',
                              'models.py', 'requirements.txt', '.travis.yml', 'models.py', '.travis.yml',
                              'multiple_songs.py', 'presets.py', 'test_API_calls.py', 'models.py', 'views.py','style.css', 'heatmapData.js', 'linechart.js', 'loadRadar.js', 'index.html', 'views.py',
                     'pull_request_template.md', '.pep8speaks.yml', '.travis.yml', 'nohup.out', 'README.md',
                     'launch.json', 'settings.json'],
                    "server":["none"]
       }


overlap_dict = defaultdict(dict)

keys = list(aut.keys())
for x in range(len(keys)):
    for y in range(x,len(keys)):
        if x != y:
            contributor_commits_1 = aut[keys[x]]
            contributor_commits_2 = aut[keys[y]]
            totalcommits = len(contributor_commits_1)
            overlap = 0
            for commit in contributor_commits_1:
                if commit in contributor_commits_2:
                    overlap+=1
            overlap_dict[keys[x]][keys[y]] = round(overlap/totalcommits * 100)


print(overlap_dict)
